# Numpy패키지와 배열(ndarray) 객체

In [12]:
import numpy as np

In [13]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

배열 객체 생성 array함수 이용

array는 동질의 데이터를 다룰 수 있는 구조

빠르다

In [31]:
np.array([1,2,3,4], dtype=np.float) #데이터 타입 지정 가능

array([1., 2., 3., 4.])

In [32]:
np.array([range(i, i + 3 ) for i in [1, 4, 7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
numpy는 기본적으로 초기화 가능한 여러가지 함수 제공
---

In [44]:
np.zeros(10) #1차원

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones((3, 5)) #3행 5열 튜플 구조를 만들고 1로 채워지는 ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full((2,3), 5)#2행 3열을 5로 채운다 초기값을 임의로 설정해 채우는 full

array([[5, 5, 5],
       [5, 5, 5]])

In [46]:
np.arange(0,10,2) #start,end,step

array([0, 2, 4, 6, 8])

np.arange는 배열을 생성한다.

In [52]:
np.linspace(0, 100, 5, dtype=int)

array([  0,  25,  50,  75, 100])

균등하게 interval을 구성할 수 있는 linspace
0 ~ 100 사이의 구간을 5개로 쪼개 4개의 구간이 생긴다

---
### 난수와 관련된 부분 
- 데이터 모의 구성 시 많이 사용하는 random 함수, 중요
--- 

In [54]:
np.random.random((3, 3)) # 3,3 -> size 3행 3열 부여

array([[0.54448513, 0.20655363, 0.27605678],
       [0.96436019, 0.98215717, 0.94029886],
       [0.810346  , 0.65445338, 0.15666951]])

random은 0 ~ 1 사이의 값을 데이터로 구성한다

In [55]:
np.random.randint(0, 10,(3,3))

array([[2, 1, 2],
       [4, 8, 3],
       [8, 8, 5]])

randint는 범위를 제공 0 ~ 9 까지의 정수 값을 3행 3열의 사이즈로 구성

In [56]:
np.random.normal(0,1, (3,3))

array([[-0.26462729, -0.07542389,  0.05377471],
       [-0.4820436 ,  1.71825651, -0.35741326],
       [ 0.14845852,  0.84296118, -1.05769372]])

normal은 정규분포를 나타낸다.종형 형태 0은 평균 1은 표준 편차  3행3열의 random 데이터

---
### 랜덤 값의 재현성 문제
seed 함수에 seed 값을 주면 재현성 문제 해결

In [62]:
np.random.seed(3)

arr1 = np.random.randint(10, size = 6) #아무것도 없으면 0 즉 start 0 end 10 정수 6개
arr2 = np.random.randint(10, size = (2,3))# 위와 같지만 2행 3열의 구조 정수 6개

print("arr1:\n%s" %arr1)
print("ndim: %d, shape: %s, size: %d, dtpye: %s\n" %
      (arr1.ndim, arr1.shape, arr1.size, arr1.dtype))
print("arr2:\n%s" %arr2)
print("ndim: %d, shape: %s, size: %d, dtpye: %s\n" %
      (arr2.ndim, arr2.shape, arr2.size, arr2.dtype))

arr1:
[8 9 3 8 8 0]
ndim: 1, shape: (6,), size: 6, dtpye: int32

arr2:
[[5 3 9]
 [9 5 7]]
ndim: 2, shape: (2, 3), size: 6, dtpye: int32



randint를 랜덤하게 만든 arr1,arr2  
ndim(차원 정보), shape(행/열, 원소의 구조 정보)  
size(원소의 개수), dtpye(data type)을 나타냄  
가장 중요한 정보는 shape -> 원소의 개수와 차원의 정보를 알 수 있다

---
### NumPy 배열 객체의 인덱싱
- 단일 원소에 접근하는 기법

In [63]:
arr1

array([8, 9, 3, 8, 8, 0])

In [64]:
arr1[0], arr1[5] #6개의 원소 0 ~ 5까지

(8, 0)

In [65]:
arr1[-5], arr1[-1] #음수를 이용하는 인덱싱 -1 ~ -6까지 

(9, 0)

음수를 이용하는 인덱싱은 마지막 데이터 접근 용이

In [67]:
arr2 # shape 2행 3열 2차원의 접근법을 알아보자

array([[5, 3, 9],
       [9, 5, 7]])

In [68]:
arr2[0,0],arr2[0,2] # [행,열]를 사용해 행/열 인덱스 정보 기술

(5, 9)

In [70]:
arr2[-1,-3], arr2[-1,1] # -1은 마지막행 

(9, 5)

In [72]:
arr2[0,0] = 9
arr2 #1행 1열의 5개 9로 바뀜 -> 새로운 값 지정 가능

array([[9, 3, 9],
       [9, 5, 7]])

---
### NumPy 배열 객체의 슬라이싱
- 부분집합을 꺼내준다 :의 연산자를 이용해 슬라이싱 한다
- start:end:step
---

In [74]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr1[0:5:1] #start0:end5:step1 배열의 부분집합 추출

array([0, 1, 2, 3, 4])

In [76]:
arr1[:5:1]#start의 0은 생략 가능

array([0, 1, 2, 3, 4])

In [77]:
arr1[:5:]#step의 1도 생략 가능

array([0, 1, 2, 3, 4])

In [79]:
arr1[:5] #end는 반드시 있어야 한다

array([0, 1, 2, 3, 4])

비어 있는 슬라이싱 연산자 사용 시  
전체집합을 부분집합으로 반환

In [80]:
arr1[2:9:2], arr1[2::2] # 2~8까지 step2, 2~끝까지 step2

(array([2, 4, 6, 8]), array([2, 4, 6, 8]))

In [81]:
arr1[::-1]# -1 step은 거꾸로 출력

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [88]:
arr1[-1:-11:-1] # -11이 포함이 되지 않으므로 9 ~ 0까지 출력 -1 == 9

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [83]:
arr1[5::-1]#end만 불포함 start는 포함 즉 5부터 거꾸로 끝까지

array([5, 4, 3, 2, 1, 0])

In [91]:
arr2 = np.arange(12).reshape(-1,4)# 0~11까지의 배열을 reshape(행/열 변환)
                                    # -1은 행이 정해지지 않았다 (행정보) 4는 열정보
                                    #즉 0~11까지의 원소를 4열을 만드니 3행이 나옴
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
arr2[:3, :4] # == 행정보  0:3:1, 열정보 0:4:1 전체의 배열을 부분 집합으로 추출

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr2[:,:] #전체 집합을 부분집합으로 추출하는 제일 쉬운 방법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
arr2[:2,:3]#행 0,1 열0,1,2 전체배열에서 2X3구조의 부분집합 추출

array([[0, 1, 2],
       [4, 5, 6]])

In [98]:
arr2[:2,2::-1] #행0,1 열2,3을 거꾸로 

array([[2, 1, 0],
       [6, 5, 4]])

In [100]:
arr2[1:,-1] # 1,2행의 -1열의 3,7,11 중 0행의 3이 빠진 7,11

array([ 7, 11])

In [102]:
arr2[-1, :], arr2[-1]#마지막행의 모든 열

(array([ 8,  9, 10, 11]), array([ 8,  9, 10, 11]))

---
### NumPy 배열 객체의 연결
- concatenate를 이용해 행과 열로 연결해 사용할 수 있다
- list안에 담아 전달 할 것 []
- axis라는 파라미터를 이용해 방향 지정 (축)
---

In [103]:
list1 = [1,2,3]
list2 = [4,5,6]

In [104]:
np.concatenate([list1,list2])

array([1, 2, 3, 4, 5, 6])

In [111]:
arr1 = np.concatenate([list1,list2], axis=0)
arr1

array([1, 2, 3, 4, 5, 6])

In [112]:
arr2 = arr1.reshape(-1,3) #reshape을 써서 2행 3열 구조로 변환
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.concatenate([arr2,arr2], axis=0) #2차원 배열구조의 axis=0일 경우 행이 합쳐짐

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [117]:
np.concatenate([arr2,arr2], axis=1)#2차원 배열구조의 axis=1일 경우 열이 합쳐짐

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [118]:
np.vstack([arr2,arr2]) #Vstack(verticals stack) = axis0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [119]:
np.hstack([arr2,arr2]) #hstack(horizontal stack)=axis1

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

---
### Numpy 배열 객체의 내장 함수 사용
- 빠른 연산이 가능한 vectorize function(벡터화 함수)
- ufunction(universal function) 사용 권장
---

In [122]:
np.random.seed(0)

arr2 = np.random.randint(1,10,(3,4))#1~10사이 랜덤 정수 3행 4열
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [123]:
np.sum(arr2), arr2.sum() #두가지 다 같은 방식 모든 정수를 더한다

(65, 65)

이 때 행의 방향과 열의 방향으로 더하고 싶다면 axis를 지정해 주어야 한다.

In [124]:
np.sum(arr2, axis=0) #axis 0의 방향 즉 열 방향으로 sum의 정보 구성이 됨

array([19, 13, 17, 16])

In [127]:
arr2.sum(axis=0)

array([19, 13, 17, 16])

In [129]:
arr2.sum(axis=1) # axis 1의 방향 즉 행 방향으로 sum의 정보 구성이 됨

array([15, 21, 29])

In [131]:
np.min(arr2, axis=0), np.max(arr2, axis=0)# axis 0은 열의 개수 만큼 나와야 한다

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

In [132]:
np.min(arr2, axis=1), np.max(arr2, axis=1)# axis 1은 행의 개수 만큼 나와야 한다

(array([1, 3, 5]), array([6, 8, 9]))

---
### Numpy 배열 객체와 브로드캐스팅
- 행과 열의 정보가 일치해야 같은 위치끼리 연산 가능
- 행열 연산을 하기 위해선 크기가 맞춰져야 한다.(shape)
- 행열 구조를 동일하게 맞춰주는 과정을 브로드캐스팅이라 한다
---

In [134]:
np.random.seed(0)

X = np.random.random((10,3))# random = 0 ~ 1 사이의 값 10행3열 구조 
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [138]:
Xmean = X.mean(axis=0)
Xmean # Xmean의 구조는 1행 3열

array([0.52101579, 0.62614181, 0.59620338])

In [139]:
Xcentered = X - Xmean # X는 10행3열 - Xmean 1행 3열
#1행 3열이 9개가 복제되서 계산됨 -> 브로드캐스팅
Xcentered

array([[ 0.02779771,  0.08904756,  0.00655999],
       [ 0.02386739, -0.20248701,  0.04969073],
       [-0.08342858,  0.26563119,  0.36745938],
       [-0.13757427,  0.16558323, -0.06730846],
       [ 0.04702877,  0.29945483, -0.52516732],
       [-0.43388649, -0.60592341,  0.23641646],
       [ 0.25714096,  0.24387034,  0.38241496],
       [ 0.27814277, -0.16466245,  0.18432579],
       [-0.40274137,  0.01377921, -0.45285009],
       [ 0.42365312, -0.10429349, -0.18154144]])

열의 평균을 구하고 그걸 뺀다 -> 중심이 이동한다  
평균을 중심으로 이동시킨다 -> 평균 중심화 예제이다  
...무슨소린지 모르겠음

---
### 부울 배열을 이용한 마스킹 연산
- 조건을 만족하는 데이터를 찾아낼 수 있다
---

In [141]:
np.random.seed(0)

X = np.random.randint(0, 10, size=(3,4))
X

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [142]:
(X > 5) & (X < 8) # 조건을 만족하는 배열 구성 -> 3행 4열 짜리의 배열을 자동으로 만듬

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True,  True]])

In [143]:
np.sum((X > 5) & (X < 8)) # True가 3개

3

In [144]:
np.sum((X > 5) | (X < 8)) # 3행 4열 12개의 원소가 모두 true

12

In [146]:
np.sum((X > 5) & (X < 8), axis=0)# 적용할 방향 지정 

array([1, 0, 1, 1])

In [147]:
np.sum((X > 5) & (X < 8), axis=1)

array([0, 1, 2])

In [149]:
X[(X > 5) & (X < 8)] #어떤 데이터가 조건에 부합하는지 불 배열과 마스킹 연산으로 
                    #추출하는 방법 

array([7, 7, 6])

---
### Numpy 배열 객체와 팬시 인덱싱
- 인덱스를 담고 있는 배열
- 인덱스 배열을 전달하게 되면 인덱스에 해당하는 데이터 추출 가능
---

In [152]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
row = np.array([0, 1 ,2])
col = np.array([1, 2, 3])
X[row]#X에 0,1,2라는 인덱싱을 줘서 1,2.3행의 결과 값이 추출

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
X[:,col] #index0이 빠진 1,2.3 즉 2,3.4열이 추출된다

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [166]:
X[row,col] #0행1열 1행2열 2행3열 값 추출

array([ 1,  6, 11])

In [168]:
X[row.reshape(-1,1),col] #reshape을 이용해 구조를 변환해도 동일한 결과값을 내는 
                        #팬싱 인덱싱

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

---
### Numpy 배열 객체와 복합 인덱싱
- 부분 집합을 찾아내는 연산이다
---


In [171]:
X = np.zeros(12).reshape((3,4)) #제로로 초기화된 3행 4열
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [172]:
X[1, 0] = 1 # 2행 1열에 데이터값 입력
X

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [175]:
X[1,[1,3]] = 1 #2행 2열4열 1으로 데이터값 입력
X

array([[0., 0., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [177]:
X[[0,2],[1,3]] = 2 # 1행 2열 3행 4열에 2 입력 (팬싱 인덱싱)
X

array([[0., 2., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 2.]])

In [179]:
X[0:3,[0,2]]=9 #팬시 인덱싱 + 슬라이싱 범위 집합 추출
#전체 행에서 1열과 3열에 9를 집어 넣는게 된다
X

array([[9., 2., 9., 0.],
       [9., 1., 9., 1.],
       [9., 0., 9., 2.]])

---
### Numpy 배열 객체의 정렬
- 정렬 기능을 내장하고 있다
---

In [184]:
np.random.seed(0)

x = np.array(np.random.randint(10, size=5))#0~9사이의 값을 5개 
x

array([5, 0, 3, 3, 7])

In [185]:
np.sort(x) #x는 바뀌지 않고 정렬된 array 반환

array([0, 3, 3, 5, 7])

In [188]:
x.sort() #x의 값이 정렬된 상태로 변경
x

array([0, 3, 3, 5, 7])

In [190]:
np.random.seed(0)

x= np.array(np.random.randint(10, size=5))
x

array([5, 0, 3, 3, 7])

In [193]:
idx = np.argsort(x)#sort된 인덱스를 전달하는 argsort함수
idx

array([1, 2, 3, 0, 4], dtype=int64)

In [195]:
x[idx]#팬시 인덱싱을 이용해 정렬도 가능

array([0, 3, 3, 5, 7])